# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.2
#   kernelspec:
#     display_name: default
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Paper Figures: Figure S1 - Movement Analysis (legacy)
#
# This notebook generates publication-ready figures for the Bazzino & Roitman sodium appetite manuscript using data assembled by `src/assemble_all_data.py`.
#
# **Figure 1: Behavioral Analysis** — Movement analysis showing heatmaps and summary plots for replete and deplete conditions across sodium concentrations.

# %%
# %load_ext IPython.extensions.autoreload
# %autoreload 2

import pathlib
from pathlib import Path
import sys
# Add src to path for importing local modules
sys.path.insert(0, str(Path("../src").resolve()))
from pickle_compat import enable_dill_pathlib_compat
enable_dill_pathlib_compat()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
import dill
from scipy import stats
from trompy import zscore
from extract_behav_parameters import smooth_array



from figure_config import (
    configure_matplotlib, COLORS, HEATMAP_CMAP_DIV,
    HEATMAP_CMAP_RED, HEATMAP_CMAP_BLUE,
    DATAFOLDER, RESULTSFOLDER, FIGSFOLDER,
    HEATMAP_VLIM_BEHAV, YLIMS_BEHAV,
    BEHAV_SMOOTH_WINDOW, SAVE_FIGS
)
from figure_plotting import (
    smooth_array, get_heatmap_data, get_mean_snips, get_auc,
    init_heatmap_figure, init_snips_figure, make_heatmap,
    plot_snips, plot_auc_summary, save_figure_atomic, print_auc_stats,
    scale_vlim_to_data, calculate_ylims,
    draw_regression_line, make_correlation_plot_behav
)

# Configure matplotlib
configure_matplotlib()
colors = COLORS  # Use shared color palette
custom_cmap_red = HEATMAP_CMAP_RED  # Use shared colormap
custom_cmap_blue = HEATMAP_CMAP_BLUE  # Use shared colormap

custom_cmap = HEATMAP_CMAP_DIV  # Use shared colormap

SAVE_FIGS = True

# %% [markdown]
# ## Load Assembled Data
#
# Load the complete dataset from the pickle file generated by the assembly script.

# %%
assembled_data_path = DATAFOLDER / "assembled_data.pickle"

with open(assembled_data_path, "rb") as f:
    data = dill.load(f)

# Extract main components
x_array = data["x_array"]
snips_photo = data["snips_photo"]
snips_movement = data["snips_movement"]
snips_angvel = data["snips_angvel"]

fits_df = data["fits_df"]
params = data.get("params", {})
metadata = data.get("metadata", {})

print(f"Loaded assembled data from {assembled_data_path}")
print(f"\nData structure:")
print(f"  - x_array shape: {x_array.shape}")
print(f"  - snips_photo shape: {snips_photo.shape}")
print(f"  - snips_angvel shape: {snips_angvel.shape}")
print(f"  - snips_movement shape: {snips_movement.shape}")
print(f"  - x_array columns: {x_array.columns.tolist()}")
print(f"  - Number of trials: {len(x_array)}")


# %% [markdown]
# ## Figure 1: Behavioral Analysis — Movement Metrics
#
# Analysis of behavioral responses (movement) showing heatmaps, snip time series, and summary AUC metrics across replete and deplete sodium conditions, separated by infusion type (10NaCl vs 45NaCl).

# %%
def zscore_to_entire_session(snips, x_array, param_name):

    mean = x_array[param_name + "_mean"].values
    std = x_array[param_name + "_std"].values
    snips_zscored = (snips - mean[:, np.newaxis]) / std[:, np.newaxis]

    return snips_zscored


# %%
# Smoothing angvel data and zscoring for plotting
snips_angvel_smoothed = smooth_array(snips_angvel, window_size=BEHAV_SMOOTH_WINDOW)
# snips_angvel_zscored = zscore(snips_angvel_smoothed, baseline_points=50)
# snips_angvel_zscored = zscore_to_entire_session(snips_angvel, x_array, "angvel")  # Z-score using entire session stats
# snips_angvel_smoothed = smooth_array(snips_angvel_zscored, window_size=BEHAV_SMOOTH_WINDOW)
snips_to_plot = np.array(snips_movement)  # Use smoothed and z-scored data for all subsequent analyses and plotting

# Parameters for visualization - MOVEMENT
# Use dynamic scaling based on actual data ranges (asymmetric, not symmetric)
# This ensures heatmaps use the full range of your data without artificial symmetry
vmin = np.nanpercentile(snips_movement, 5)  # 5th percentile for lower bound
vmax = np.nanpercentile(snips_movement, 95)  # 95th percentile for upper bound
vlim = (vmin, vmax)
print(f"Calculated asymmetric vlims: vmin={vmin:.4f}, vmax={vmax:.4f}")
# vlim = (-0.75, 0.75) # for zscored data
vlim = (1, 6)

# Calculate dynamic y-limits based on all snips data - MOVEMENT
print("\n" + "="*60)
print("CALCULATING Y-LIMITS FOR TIME SERIES PLOTS")
print("="*60)

# Get all condition/infusion combinations to compute limits
rep_10, rep_45 = get_mean_snips(snips_movement, x_array, "replete")
dep_10, dep_45 = get_mean_snips(snips_movement, x_array, "deplete")

# Calculate y-limits based on all snips with 5% padding
calc_ylims = calculate_ylims([rep_10, rep_45, dep_10, dep_45], pad_percentage=5)

print(f"  Data range (min, max): ({np.nanmin(snips_movement):.4f}, {np.nanmax(snips_movement):.4f})")
print(f"  Calculated y-limits: {calc_ylims}")
print("="*60 + "\n")

# Use calculated limits or override with fixed values if preferred
ylims = calc_ylims
ylims = (0, 8)


# %%
### 1A. Heatmaps — Replete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Replete + 10NaCl
heatmap_data_rep_10 = get_heatmap_data(snips_to_plot, x_array, "replete", "10NaCl")
replete_10_auc = get_auc(heatmap_data_rep_10)
make_heatmap(heatmap_data_rep_10, ax1, vlim, inf_bar=True, cmap=custom_cmap_red)

# Replete + 45NaCl
heatmap_data_rep_45 = get_heatmap_data(snips_to_plot, x_array, "replete", "45NaCl")
replete_45_auc = get_auc(heatmap_data_rep_45)
make_heatmap(heatmap_data_rep_45, ax2, vlim, cbar_ax=cbar_ax, cmap=custom_cmap_red)

if SAVE_FIGS:
    save_figure_atomic(f, "figS1_heatmap_movement_replete", FIGSFOLDER)

# %%
### 1B. Heatmaps — Deplete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Deplete + 10NaCl
heatmap_data_dep_10 = get_heatmap_data(snips_to_plot, x_array, "deplete", "10NaCl")
deplete_10_auc = get_auc(heatmap_data_dep_10)
make_heatmap(heatmap_data_dep_10, ax1, vlim, inf_bar=True, cmap=custom_cmap_red)

# Deplete + 45NaCl
heatmap_data_dep_45 = get_heatmap_data(snips_to_plot, x_array, "deplete", "45NaCl")
deplete_45_auc = get_auc(heatmap_data_dep_45)
make_heatmap(heatmap_data_dep_45, ax2, vlim, cbar_ax=cbar_ax, cmap=custom_cmap_red)

if SAVE_FIGS:
    save_figure_atomic(f, "figS1_heatmap_movement_deplete", FIGSFOLDER)

# %%
### Z-scored Angular Velocity (baseline normalized) - Replete Condition

# Z-score angular velocity to baseline (first 50 bins)
baseline_end = 50
snips_movement_zscored = zscore(snips_movement, baseline_points=50)
snips_movement_zscored = np.array(snips_movement_zscored)

# Calculate symmetric vlims for z-scored data
vmin_zscored = np.nanpercentile(snips_movement_zscored, 5)
vmax_zscored = np.nanpercentile(snips_movement_zscored, 95)
# Make symmetric around zero
vmax_zscored = max(abs(vmin_zscored), abs(vmax_zscored))
vmin_zscored = -vmax_zscored
vlim_zscored = (vmin_zscored, vmax_zscored)

print(f"Z-scored Angular Velocity - Symmetric vlims: vmin={vmin_zscored:.4f}, vmax={vmax_zscored:.4f}")

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Replete + 10NaCl (z-scored)
heatmap_data_rep_10_zscored = get_heatmap_data(snips_movement_zscored, x_array, "replete", "10NaCl")
make_heatmap(heatmap_data_rep_10_zscored, ax1, vlim_zscored, inf_bar=True, cmap='RdBu_r')

# Replete + 45NaCl (z-scored)
heatmap_data_rep_45_zscored = get_heatmap_data(snips_movement_zscored, x_array, "replete", "45NaCl")
make_heatmap(heatmap_data_rep_45_zscored, ax2, vlim_zscored, cbar_ax=cbar_ax, cmap='RdBu_r')

ax1.set_title("Replete + 10NaCl (z-scored)", fontsize=10)
ax2.set_title("Replete + 45NaCl (z-scored)", fontsize=10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_heatmap_movement_zscored_replete", FIGSFOLDER)


# %%
### Z-scored Angular Velocity (baseline normalized) - Deplete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Deplete + 10NaCl (z-scored)
heatmap_data_dep_10_zscored = get_heatmap_data(snips_movement_zscored, x_array, "deplete", "10NaCl")
make_heatmap(heatmap_data_dep_10_zscored, ax1, vlim_zscored, inf_bar=True, cmap='RdBu_r')

# Deplete + 45NaCl (z-scored)
heatmap_data_dep_45_zscored = get_heatmap_data(snips_movement_zscored, x_array, "deplete", "45NaCl")
make_heatmap(heatmap_data_dep_45_zscored, ax2, vlim_zscored, cbar_ax=cbar_ax, cmap='RdBu_r')

ax1.set_title("Deplete + 10NaCl (z-scored)", fontsize=10)
ax2.set_title("Deplete + 45NaCl (z-scored)", fontsize=10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_heatmap_movement_zscored_deplete", FIGSFOLDER)


# %%
### 1C. Time Series Snips — Replete Condition

# Get animal-averaged snips for replete
snips_rep_10, snips_rep_45 = get_mean_snips(snips_to_plot, x_array, "replete")

f, ax = init_snips_figure()
plot_snips(snips_rep_10, snips_rep_45, ax, colors[0], colors[1], ylims)

if SAVE_FIGS:
    save_figure_atomic(f, "figS1_snips_movement_replete", FIGSFOLDER)

# %%
### 1D. Time Series Snips — Deplete Condition

# Get animal-averaged snips for deplete
snips_dep_10, snips_dep_45 = get_mean_snips(snips_to_plot, x_array, "deplete")

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3], ylims, yscalebar=[6,7], xscalebar=True)

if SAVE_FIGS:
    save_figure_atomic(f, "figS1_snips_movement_deplete", FIGSFOLDER)


# %%
def get_time_moving_by_group(x_array, condition, infusiontype):
    
    return (
        x_array
        .query("condition == @condition and infusiontype == @infusiontype")
        .groupby("id")
        .time_moving
        .mean()
        .values
    )


# %%
### 1E. AUC Summary — Bar Plot with Individual Data Points

# Organize AUCs by condition
replete_aucs = [get_time_moving_by_group(x_array, "replete", "10NaCl"),
                get_time_moving_by_group(x_array, "replete", "45NaCl")]
deplete_aucs = [get_time_moving_by_group(x_array, "deplete", "10NaCl"),
                get_time_moving_by_group(x_array, "deplete", "45NaCl")]
                                         
aucs = [replete_aucs, deplete_aucs]

f, ax = plot_auc_summary(aucs, colors, ylabel="Time moving ")
# f.suptitle("Ang vel — AUC Summary", fontsize=10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_auc_movement_summary", FIGSFOLDER)

# Print summary statistics
auc_labels = [
    f"Replete + 10NaCl (n={len(replete_aucs[0])})",
    f"Replete + 45NaCl (n={len(replete_aucs[1])})",
    f"Deplete + 10NaCl (n={len(deplete_aucs[0])})",
    f"Deplete + 45NaCl (n={len(deplete_aucs[1])})"
]
auc_arrays = [replete_aucs[0], replete_aucs[1], deplete_aucs[0], deplete_aucs[1]]
print_auc_stats(auc_arrays, auc_labels, title="Figure 1 — Movement Summary Statistics")


# %%
### Correlation plots — Time moving across trials

def make_auc_data_per_trial(x_array, condition, infusiontype):
    
    return (
        x_array
        .query("condition == @condition & infusiontype == @infusiontype")
        .groupby("trial")
        .time_moving
        .mean()
        .values
    )
    
replete_10 = make_auc_data_per_trial(x_array, "replete", "10NaCl")
replete_45 = make_auc_data_per_trial(x_array, "replete", "45NaCl")
deplete_10 = make_auc_data_per_trial(x_array, "deplete", "10NaCl")
deplete_45 = make_auc_data_per_trial(x_array, "deplete", "45NaCl")

f = make_correlation_plot_behav(replete_10, replete_45, colors[0], colors[1], yaxis=True)
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_movement_replete", FIGSFOLDER)
    
f = make_correlation_plot_behav(deplete_10, deplete_45, colors[2], colors[3])
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_movement_deplete", FIGSFOLDER)

# %%
### Model fits on time-moving by trial data with fit-quality checks
from scipy.optimize import curve_fit
from scipy.stats import pearsonr

def _linear_model(x, m, b):
    return m * x + b

def _exp_model(x, a, b, c):
    return a * np.exp(b * x) + c

def _sigmoid_model(x, L, k, x0, b):
    z = np.clip(-k * (x - x0), -60, 60)
    return L / (1 + np.exp(z)) + b

def _safe_pearson(y_true, y_pred):
    if np.allclose(np.std(y_true), 0) or np.allclose(np.std(y_pred), 0):
        return np.nan, np.nan
    return pearsonr(y_true, y_pred)

def _model_metrics(y_true, y_pred, n_params):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    n = len(y_true)
    residuals = y_true - y_pred
    sse = np.nansum(residuals ** 2)
    sse = max(float(sse), 1e-12)
    rmse = np.sqrt(sse / n) if n > 0 else np.nan
    aic = n * np.log(sse / n) + 2 * n_params if n > 0 else np.nan
    bic = n * np.log(sse / n) + n_params * np.log(n) if n > 1 else np.nan
    aicc = aic + (2 * n_params * (n_params + 1)) / (n - n_params - 1) if n > (n_params + 1) else np.nan
    return rmse, aic, aicc, bic

def _fit_linear(x, y):
    try:
        m, b = np.polyfit(x, y, 1)
        yhat = _linear_model(x, m, b)
        r, p = _safe_pearson(y, yhat)
        rmse, aic, aicc, bic = _model_metrics(y, yhat, n_params=2)
        return {"r": r, "p": p, "rmse": rmse, "aic": aic, "aicc": aicc, "bic": bic, "params": np.array([m, b]), "pcov": None}
    except Exception:
        return {"r": np.nan, "p": np.nan, "rmse": np.nan, "aic": np.nan, "aicc": np.nan, "bic": np.nan, "params": np.array([np.nan, np.nan]), "pcov": None}

def _fit_curve(model_name, model_func, x, y):
    try:
        if model_name == "exponential":
            p0 = [np.ptp(y) if np.ptp(y) != 0 else 1.0, 0.05, np.min(y)]
            bounds = ([-np.inf, -np.inf, -np.inf], [np.inf, np.inf, np.inf])
            n_params = 3
        elif model_name == "sigmoidal":
            p0 = [np.ptp(y) if np.ptp(y) != 0 else 1.0, 0.2, np.median(x), np.min(y)]
            bounds = ([-np.inf, -np.inf, np.min(x), -np.inf], [np.inf, np.inf, np.max(x), np.inf])
            n_params = 4
        else:
            raise ValueError(f"Unknown model: {model_name}")

        params, pcov = curve_fit(model_func, x, y, p0=p0, bounds=bounds, maxfev=30000)
        yhat = model_func(x, *params)
        r, p = _safe_pearson(y, yhat)
        rmse, aic, aicc, bic = _model_metrics(y, yhat, n_params=n_params)
        return {"r": r, "p": p, "rmse": rmse, "aic": aic, "aicc": aicc, "bic": bic, "params": params, "pcov": pcov}
    except Exception:
        n_params = 3 if model_name == "exponential" else 4
        return {"r": np.nan, "p": np.nan, "rmse": np.nan, "aic": np.nan, "aicc": np.nan, "bic": np.nan, "params": np.full(n_params, np.nan), "pcov": None}

def _sigmoid_quality_checks(x, params, pcov):
    if params is None or len(params) != 4 or np.any(~np.isfinite(params)):
        return False, "fit_failed", {"x0_interior": False, "k_plausible": False, "ci_finite": False, "asymptotes_covered": False}

    L, k, x0, b = params
    x_min, x_max = float(np.min(x)), float(np.max(x))
    x_range = max(x_max - x_min, 1.0)
    edge_margin = 0.15 * x_range
    x0_interior = (x_min + edge_margin) <= x0 <= (x_max - edge_margin)
    k_plausible = np.isfinite(k) and (0.02 <= abs(k) <= 2.5)

    ci_finite = False
    if pcov is not None:
        diag = np.diag(pcov)
        if np.all(np.isfinite(diag)) and np.all(diag >= 0):
            se = np.sqrt(diag)
            ci_finite = np.all(np.isfinite(se)) and np.all(se > 0)

    amplitude = abs(L)
    if amplitude < 1e-8:
        asymptotes_covered = False
    else:
        lower_asym = min(b, b + L)
        upper_asym = max(b, b + L)
        y_start = _sigmoid_model(np.array([x_min]), L, k, x0, b)[0]
        y_end = _sigmoid_model(np.array([x_max]), L, k, x0, b)[0]

        tol = 0.2
        start_low = abs(y_start - lower_asym) / amplitude <= tol
        start_high = abs(y_start - upper_asym) / amplitude <= tol
        end_low = abs(y_end - lower_asym) / amplitude <= tol
        end_high = abs(y_end - upper_asym) / amplitude <= tol

        start_side = "low" if start_low else ("high" if start_high else None)
        end_side = "low" if end_low else ("high" if end_high else None)
        asymptotes_covered = (start_side is not None) and (end_side is not None) and (start_side != end_side)

    checks = {
        "x0_interior": bool(x0_interior),
        "k_plausible": bool(k_plausible),
        "ci_finite": bool(ci_finite),
        "asymptotes_covered": bool(asymptotes_covered),
    }

    failed = [name for name, ok in checks.items() if not ok]
    is_valid = len(failed) == 0
    reasons = "ok" if is_valid else ";".join(failed)
    return is_valid, reasons, checks

fit_inputs = {
    "Replete + 10NaCl": replete_10,
    "Replete + 45NaCl": replete_45,
    "Deplete + 10NaCl": deplete_10,
    "Deplete + 45NaCl": deplete_45,
}

rows = []
sigmoid_diagnostics = []

for condition_label, y in fit_inputs.items():
    y = np.asarray(y, dtype=float)
    x = np.arange(1, len(y) + 1, dtype=float)

    lin = _fit_linear(x, y)
    rows.append({
        "Condition": condition_label,
        "Model": "Linear",
        "r": lin["r"],
        "p": lin["p"],
        "RMSE": lin["rmse"],
        "AICc": lin["aicc"],
        "BIC": lin["bic"],
        "Sigmoid_valid": np.nan,
        "Sigmoid_flags": "",
    })

    exp_fit = _fit_curve("exponential", _exp_model, x, y)
    rows.append({
        "Condition": condition_label,
        "Model": "Exponential",
        "r": exp_fit["r"],
        "p": exp_fit["p"],
        "RMSE": exp_fit["rmse"],
        "AICc": exp_fit["aicc"],
        "BIC": exp_fit["bic"],
        "Sigmoid_valid": np.nan,
        "Sigmoid_flags": "",
    })

    sig_fit = _fit_curve("sigmoidal", _sigmoid_model, x, y)
    is_valid, reasons, checks = _sigmoid_quality_checks(x, sig_fit["params"], sig_fit["pcov"])
    rows.append({
        "Condition": condition_label,
        "Model": "Sigmoidal",
        "r": sig_fit["r"],
        "p": sig_fit["p"],
        "RMSE": sig_fit["rmse"],
        "AICc": sig_fit["aicc"],
        "BIC": sig_fit["bic"],
        "Sigmoid_valid": is_valid,
        "Sigmoid_flags": reasons,
    })

    L, k, x0, b = sig_fit["params"] if len(sig_fit["params"]) == 4 else [np.nan, np.nan, np.nan, np.nan]
    sigmoid_diagnostics.append({
        "Condition": condition_label,
        "L": L,
        "k": k,
        "x0": x0,
        "b": b,
        "Sigmoid_valid": is_valid,
        "Sigmoid_flags": reasons,
        "x0_interior": checks["x0_interior"],
        "k_plausible": checks["k_plausible"],
        "ci_finite": checks["ci_finite"],
        "asymptotes_covered": checks["asymptotes_covered"],
    })

fit_results = pd.DataFrame(rows)
fit_results["AICc_rank"] = fit_results.groupby("Condition")["AICc"].rank(method="dense")
fit_results["Best_by_AICc"] = fit_results["AICc_rank"] == 1

for col in ["r", "p", "RMSE", "AICc", "BIC", "AICc_rank"]:
    fit_results[col] = fit_results[col].round(4)

print("Model fit results (time moving by trial) with quality checks:")
display(fit_results)

sigmoid_params_table = pd.DataFrame(sigmoid_diagnostics)
sigmoid_params_table[["L", "k", "x0", "b"]] = sigmoid_params_table[["L", "k", "x0", "b"]].round(4)

print("Sigmoidal fit parameters (time moving by trial) with validity checks:")
display(sigmoid_params_table)

# %%
### Best valid model per condition (compact summary)
summary_rows = []

for condition_label, group in fit_results.groupby("Condition"):
    group = group.copy()
    group["Is_valid_for_selection"] = np.where(
        group["Model"] == "Sigmoidal",
        group["Sigmoid_valid"].fillna(False),
        True,
    )

    valid_group = group[group["Is_valid_for_selection"] == True]
    if len(valid_group) > 0 and valid_group["AICc"].notna().any():
        best = valid_group.sort_values("AICc", ascending=True).iloc[0]
        selection_reason = "best_valid_by_AICc"
    else:
        best = group.sort_values("AICc", ascending=True).iloc[0]
        selection_reason = "fallback_no_valid_model"

    summary_rows.append({
        "Condition": condition_label,
        "Selected_Model": best["Model"],
        "Selection_Reason": selection_reason,
        "r": best["r"],
        "p": best["p"],
        "RMSE": best["RMSE"],
        "AICc": best["AICc"],
        "BIC": best["BIC"],
        "Sigmoid_valid": best["Sigmoid_valid"],
        "Sigmoid_flags": best["Sigmoid_flags"],
    })

best_model_summary = pd.DataFrame(summary_rows)
for col in ["r", "p", "RMSE", "AICc", "BIC"]:
    best_model_summary[col] = best_model_summary[col].round(4)

print("Best valid model per condition (AICc-based):")
display(best_model_summary)


# %%
### Time Above Angular Velocity Threshold Summary — Bar Plot (per-rat means)

# Calculate mean time above threshold per rat, then organize by condition/infusion
# This matches the approach used for AUC where we get the mean per rat first

def get_mean_time_above_per_rat(x_array, condition, infusion):
    """Get mean time above threshold per rat for a given condition/infusion."""
    subset = x_array[(x_array['condition'] == condition) & (x_array['infusiontype'] == infusion)]
    time_above_per_rat = subset.groupby('id')['time_above_angvel_threshold'].mean().values
    return time_above_per_rat

# Get per-rat means for each condition/infusion combination
rep_10_time_above = get_mean_time_above_per_rat(x_array, "replete", "10NaCl")
rep_45_time_above = get_mean_time_above_per_rat(x_array, "replete", "45NaCl")
dep_10_time_above = get_mean_time_above_per_rat(x_array, "deplete", "10NaCl")
dep_45_time_above = get_mean_time_above_per_rat(x_array, "deplete", "45NaCl")

# Organize by condition
replete_time_above = [rep_10_time_above, rep_45_time_above]
deplete_time_above = [dep_10_time_above, dep_45_time_above]
time_above_data = [replete_time_above, deplete_time_above]

f, ax = plot_auc_summary(time_above_data, colors, ylabel="")

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_time_above_threshold_summary_perrat", FIGSFOLDER)


# Print summary statistics
time_labels = [
    f"Replete + 10NaCl (n={len(rep_10_time_above)} rats)",
    f"Replete + 45NaCl (n={len(rep_45_time_above)} rats)",
    f"Deplete + 10NaCl (n={len(dep_10_time_above)} rats)",
    f"Deplete + 45NaCl (n={len(dep_45_time_above)} rats)"
]
time_arrays = [rep_10_time_above, rep_45_time_above, dep_10_time_above, dep_45_time_above]
print_auc_stats(time_arrays, time_labels, title="Time Above Threshold Summary Statistics (per-rat means)")

# %% [markdown]
# ## Organization
#
# This notebook generates **Figure 1 (Movement Analysis)** only. Each subsequent figure has its own dedicated notebook:
#
# - **figure_1_paper.ipynb**: Movement analysis (current)
# - **figure_2_paper.ipynb**: Photometry (dopamine) analysis  
# - **figure_3_paper.ipynb**: Neural-behavioral correlation
# - **figure_4_paper.ipynb**: Transition analysis
# - **figure_5_paper.ipynb**: Cluster analysis
#
# All notebooks share common settings and functions from:
# - `src/figure_config.py` — Colors, paths, parameters
# - `src/figure_plotting.py` — Data extraction and plotting functions
#
# This keeps each figure focused and manageable, while reducing code duplication.

# %%
# Configuration for Figure Saving
# ───────────────────────────────────────────────────────────────────────
# The SAVE_FIGS setting is loaded from figure_config.py
# Figures are saved in two formats:
#   - PDF for publication (vector format, smaller file size)
#   - PNG for presentations (raster format, high DPI for screen)
#
# All figures follow naming convention:
#   fig{number}_{description}.{pdf|png}
#
# Example:
#   fig1_heatmap_movement_replete.pdf
#   fig1_snips_movement_replete.png
# ───────────────────────────────────────────────────────────────────────

print(f"\nFigure saving is currently: {'ENABLED' if SAVE_FIGS else 'DISABLED'}")
print(f"Figure output folder: {FIGSFOLDER}")
if SAVE_FIGS:
    print("All generated figures will be saved in both PDF and PNG formats.")
else:
    print("To save figures, set SAVE_FIGS = True in src/figure_config.py")

# %%

# %% [markdown]
# ## Figure 1 (Bonus): Movement vs Angular Velocity Comparison
#
# Comparison of head rotation (angular velocity) with body movement to explore the relationship between these metrics across conditions.

# %%

# %%
### Per-Rat Time Series: Deplete + 45NaCl (4 metrics across trials)

n_rats = len(rats)
fig, axes = plt.subplots(n_rats, 4, figsize=(14, 2.5*n_rats))

# Handle case where there's only one rat (axes would not be 2D)
if n_rats == 1:
    axes = axes.reshape(1, -1)

# Column labels
col_labels = ['AUC Movement', 'Time Moving', 'AUC Angular Vel', 'Time Above Angvel']

# Add column titles at the top
for col, label in enumerate(col_labels):
    axes[0, col].annotate(label, xy=(0.5, 1.15), xycoords='axes fraction',
                         ha='center', fontsize=11, fontweight='bold')

# Plot each rat
for row, rat in enumerate(rats):
    rat_data = x_dep45[x_dep45['id'] == rat].reset_index(drop=True)
    rat_color = rat_colors[rat]
    trial_nums = range(len(rat_data))
    
    # Column 1: AUC Movement
    axes[row, 0].plot(trial_nums, rat_data['auc_movement'], 'o-', 
                     color=rat_color, markersize=4, linewidth=1, alpha=0.7)
    axes[row, 0].set_ylabel(f'Rat {rat}', fontsize=9, fontweight='bold', labelpad=10)
    axes[row, 0].grid(True, alpha=0.3)
    axes[row, 0].tick_params(labelsize=8)
    if row == n_rats - 1:
        axes[row, 0].set_xlabel('Trial #', fontsize=9)
    
    # Column 2: Time Moving
    axes[row, 1].plot(trial_nums, rat_data['time_moving'], 'o-', 
                     color=rat_color, markersize=4, linewidth=1, alpha=0.7)
    axes[row, 1].set_ylim([0, 1])
    axes[row, 1].grid(True, alpha=0.3)
    axes[row, 1].tick_params(labelsize=8)
    if row == n_rats - 1:
        axes[row, 1].set_xlabel('Trial #', fontsize=9)
    
    # Column 3: AUC Angular Velocity (if available)
    if 'auc_angvel' in rat_data.columns:
        axes[row, 2].plot(trial_nums, rat_data['auc_angvel'], 'o-', 
                         color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        axes[row, 2].grid(True, alpha=0.3)
        axes[row, 2].tick_params(labelsize=8)
        if row == n_rats - 1:
            axes[row, 2].set_xlabel('Trial #', fontsize=9)
    
    # Column 4: Time Above Angular Velocity Threshold (if available)
    if 'time_above_angvel_threshold' in rat_data.columns:
        axes[row, 3].plot(trial_nums, rat_data['time_above_angvel_threshold'], 'o-', 
                         color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        axes[row, 3].set_ylim([0, 1])
        axes[row, 3].grid(True, alpha=0.3)
        axes[row, 3].tick_params(labelsize=8)
        if row == n_rats - 1:
            axes[row, 3].set_xlabel('Trial #', fontsize=9)

fig.suptitle(f'Deplete + 45NaCl: Per-Rat Metrics Across Trials (n={len(x_dep45)} trials)', 
             fontsize=12, fontweight='bold', y=0.995)

plt.tight_layout()
if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_deplete45_perrat_timeseries", FIGSFOLDER)
plt.show()

# %%

# %%
### Per-Rat Angular Velocity Threshold Analysis: Deplete + 45NaCl

# Import the threshold function from assemble_all_data
from extract_behav_parameters import smooth_array

# Define different angular velocity thresholds to test
angvel_thresholds = [0.5, 1.0, 1.5, 2.0]
s, e = 50, 150  # Same bin range as used in assembly

# Prepare data: smooth angular velocity snips if not already smoothed
snips_angvel_smooth = smooth_array(snips_angvel, window_size=5)

# Pre-calculate time above threshold for all threshold values and all trials
threshold_data = {}
for thresh in angvel_thresholds:
    time_above = []
    for i in range(snips_angvel_smooth.shape[0]):
        snip = snips_angvel_smooth[i, s:e]
        proportion = len([x for x in snip if x > thresh]) / len(snip)
        time_above.append(proportion)
    threshold_data[thresh] = np.array(time_above)

# Create a dictionary of transition points by rat ID from fits_df
transition_points = {}
if fits_df is not None and len(fits_df) > 0:
    for _, row in fits_df.iterrows():
        transition_points[row['id']] = row['x0_orig']

# Create per-rat figure with one column per threshold
n_rats = len(rats)
fig, axes = plt.subplots(n_rats, len(angvel_thresholds), figsize=(12, 2.5*n_rats))

# Handle case where there's only one rat (axes would not be 2D)
if n_rats == 1:
    axes = axes.reshape(1, -1)

# Column labels with threshold values
col_labels = [f'Threshold = {t}°/frame' for t in angvel_thresholds]

# Add column titles at the top
for col, label in enumerate(col_labels):
    axes[0, col].annotate(label, xy=(0.5, 1.15), xycoords='axes fraction',
                         ha='center', fontsize=10, fontweight='bold')

# Plot each rat across all thresholds
for row, rat in enumerate(rats):
    rat_indices = x_dep45[x_dep45['id'] == rat].index.tolist()
    rat_color = rat_colors[rat]
    trial_nums = range(len(rat_indices))
    
    for col, thresh in enumerate(angvel_thresholds):
        ax = axes[row, col]
        rat_thresh_data = threshold_data[thresh][rat_indices]
        
        ax.plot(trial_nums, rat_thresh_data, 'o-', 
               color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        ax.set_ylim([0, 1])
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=8)
        
        # Add transition point line if available for this rat
        if rat in transition_points:
            x0 = transition_points[rat]
            ax.axvline(x=x0, color='red', linestyle='--', linewidth=1.5, alpha=0.7, label=f'x0={x0:.1f}')
            ax.legend(fontsize=7, loc='upper right')
        
        # Add rat label on first column
        if col == 0:
            ax.set_ylabel(f'Rat {rat}', fontsize=9, fontweight='bold', labelpad=10)
        
        # Add x-axis label on bottom row
        if row == n_rats - 1:
            ax.set_xlabel('Trial #', fontsize=9)

fig.suptitle(f'Deplete + 45NaCl: Per-Rat Angular Velocity Threshold Analysis (n={len(x_dep45)} trials)', 
             fontsize=12, fontweight='bold', y=0.995)

plt.tight_layout()
if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_deplete45_perrat_angvel_thresholds", FIGSFOLDER)
plt.show()

print(f"Angular velocity threshold analysis completed.")
print(f"Thresholds tested: {angvel_thresholds} degrees/frame")
print(f"Data window: bins {s}-{e}")
print(f"Number of rats: {n_rats}")
print(f"\nTransition points available for:")
for rat in rats:
    if rat in transition_points:
        print(f"  Rat {rat}: x0_orig = {transition_points[rat]:.2f} trials")
    else:
        print(f"  Rat {rat}: no transition fit available")

# %%
snips_simba_app = snips_simba[x_array.query("condition == 'deplete' and infusiontype == '10NaCl'").index]
sns.heatmap(snips_simba_app, cmap='viridis')

# %%
snips_simba_switch = snips_simba[x_array.query("condition == 'deplete' and infusiontype == '45NaCl'").index]
sns.heatmap(snips_simba_switch, cmap='viridis')

# %%
snips_simba_replete = snips_simba[x_array.query("condition == 'replete'").index]
sns.heatmap(snips_simba_replete, cmap='viridis')

# %%
for id in x_array['id'].unique():
    print(f"Rat {id}:")
    rat_snips = snips_simba[x_array.query("id == @id").index]
    sns.heatmap(rat_snips, cmap='viridis')
    plt.title(f"Rat {id} - SIMBA Snips")
    plt.show()

# %%
