# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.2
#   kernelspec:
#     display_name: default
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Paper Figures: Figure 1 - Movement (SIMBA) Analysis
#
# This notebook generates publication-ready figures for the Bazzino & Roitman sodium appetite manuscript using data assembled by `src/assemble_all_data.py`.
#
# **Figure 1: Behavioral (SIMBA) Analysis** — SIMBA analysis (appetitive) showing heatmaps and summary plots for replete and deplete conditions across sodium concentrations.

# %%
# %load_ext IPython.extensions.autoreload
# %autoreload 2

import pathlib
from pathlib import Path
import sys
# Add src to path for importing local modules
sys.path.insert(0, str(Path("../src").resolve()))
from pickle_compat import enable_dill_pathlib_compat
enable_dill_pathlib_compat()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns
import dill
from scipy import stats
from scipy.ndimage import gaussian_filter1d
from scipy.spatial.distance import cdist
from sklearn.manifold import MDS
from trompy import zscore, save_figure_atomic
from extract_behav_parameters import smooth_array

from distance_matrix import (make_metric_matrix, get_group_matrix_diffs,
                             GROUP_ORDER, GROUP_LABELS,
                             compute_mds_coordinates
)

from figure_config import (
    configure_matplotlib, COLORS, HEATMAP_CMAP_DIV,
    HEATMAP_CMAP_RED, HEATMAP_CMAP_BLUE,
    DATAFOLDER, RESULTSFOLDER, FIGSFOLDER,
    HEATMAP_VLIM_BEHAV, YLIMS_BEHAV,
    BEHAV_SMOOTH_WINDOW, SAVE_FIGS
)
from figure_plotting import (
    smooth_array, get_heatmap_data, get_mean_snips, get_auc,
    init_heatmap_figure, init_snips_figure, make_heatmap,
    plot_snips, plot_auc_summary, print_auc_stats,
    scale_vlim_to_data, calculate_ylims,
    draw_regression_line, make_correlation_plot_simba,
    make_correlation_plot_simba_1group, make_mds_plot,
    make_euclidean_distance_heatmap_all_rats, make_euclidean_distance_heatmap_averaged
)

# Configure matplotlib
configure_matplotlib()
colors = COLORS  # Use shared color palette
custom_cmap_red = HEATMAP_CMAP_RED  # Use shared colormap
custom_cmap_blue = HEATMAP_CMAP_BLUE  # Use shared colormap

custom_cmap = HEATMAP_CMAP_DIV  # Use shared diverging colormap

SAVE_FIGS = True
SIMBA_METRIC = "median" # other options...

# %% [markdown]
# ## Load Assembled Data
#
# Load the complete dataset from the pickle file generated by the assembly script.

# %%
assembled_data_path = DATAFOLDER / "assembled_data.pickle"

with open(assembled_data_path, "rb") as f:
    data = dill.load(f)

# Extract main components
x_array = data["x_array"]
snips_photo = data["snips_photo"]

if SIMBA_METRIC == "zscore":
    snips_simba = data["snips_simba_zscore"]
    simba_col = "simba_zscore_mean"
elif SIMBA_METRIC == "median":
    snips_simba = data["snips_simba_shifted_baseline"]
    simba_col = "simba_median_balance"
elif SIMBA_METRIC == "raw":
    snips_simba = data["snips_simba_raw"]
    simba_col = "simba_raw_mean"
    custom_cmap = HEATMAP_CMAP_RED  # Use red colormap for raw metric
else:
    raise ValueError(f"Unknown SIMBA_METRIC: {SIMBA_METRIC}")

fits_df = data["fits_df"]
params = data.get("params", {})
metadata = data.get("metadata", {})

print(f"Loaded assembled data from {assembled_data_path}")
print(f"\nData structure:")
print(f"  - x_array shape: {x_array.shape}")
print(f"  - snips_photo shape: {snips_photo.shape}")
print(f"  - snips_simba shape: {snips_simba.shape}")
print(f"  - x_array columns: {x_array.columns.tolist()}")
print(f"  - Number of trials: {len(x_array)}")


# %%
data.keys()

# %% [markdown]
# ## Figure 1: Behavioral Analysis — SIMBA Metrics
#
# Analysis of behavioral responses (movement) showing heatmaps, snip time series, and summary AUC metrics across replete and deplete sodium conditions, separated by infusion type (10NaCl vs 45NaCl).

# %%
snips_to_plot = np.array(smooth_array(snips_simba))  # Use smoothed and z-scored data for all subsequent analyses and plotting

# Parameters for visualization - MOVEMENT
# Use dynamic scaling based on actual data ranges (asymmetric, not symmetric)
# This ensures heatmaps use the full range of your data without artificial symmetry
vmin = np.nanpercentile(snips_to_plot, 5)  # 5th percentile for lower bound
vmax = np.nanpercentile(snips_to_plot, 95)  # 95th percentile for upper bound
print(f"Calculated asymmetric vlims: vmin={vmin:.4f}, vmax={vmax:.4f}")

if SIMBA_METRIC == "zscore":
    vlim = (-1, 1)
elif SIMBA_METRIC == "median":
    vlim = (-0.2, 0.2)
elif SIMBA_METRIC == "raw":
    vlim = (0, 0.4)  # Use calculated asymmetric limits for raw metric
else:
    vlim = (vmin, vmax)  # Use calculated asymmetric limits for other metrics

# Calculate dynamic y-limits based on all snips data - MOVEMENT
print("\n" + "="*60)
print("CALCULATING Y-LIMITS FOR TIME SERIES PLOTS")
print("="*60)

# Get all condition/infusion combinations to compute limits
rep_10, rep_45 = get_mean_snips(snips_to_plot, x_array, "replete")
dep_10, dep_45 = get_mean_snips(snips_to_plot, x_array, "deplete")

# Calculate y-limits based on all snips with 5% padding
calc_ylims = calculate_ylims([rep_10, rep_45, dep_10, dep_45], pad_percentage=5)

print(f"  Data range (min, max): ({np.nanmin(snips_to_plot):.4f}, {np.nanmax(snips_to_plot):.4f})")
print(f"  Calculated y-limits: {calc_ylims}")
print("="*60 + "\n")



# %%
### 1A. Heatmaps — Replete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Replete + 10NaCl
heatmap_data_rep_10 = get_heatmap_data(snips_to_plot, x_array, "replete", "10NaCl")
replete_10_auc = get_auc(heatmap_data_rep_10)
make_heatmap(heatmap_data_rep_10, ax1, vlim, inf_bar=True, cmap=custom_cmap)

# Replete + 45NaCl
heatmap_data_rep_45 = get_heatmap_data(snips_to_plot, x_array, "replete", "45NaCl")
replete_45_auc = get_auc(heatmap_data_rep_45)
make_heatmap(heatmap_data_rep_45, ax2, vlim, cbar_ax=cbar_ax, cmap=custom_cmap)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_heatmap_simba_replete", FIGSFOLDER)

# %%
### 1B. Heatmaps — Deplete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Deplete + 10NaCl
heatmap_data_dep_10 = get_heatmap_data(snips_to_plot, x_array, "deplete", "10NaCl")
deplete_10_auc = get_auc(heatmap_data_dep_10)
make_heatmap(heatmap_data_dep_10, ax1, vlim, inf_bar=True, cmap=custom_cmap)

# Deplete + 45NaCl
heatmap_data_dep_45 = get_heatmap_data(snips_to_plot, x_array, "deplete", "45NaCl")
deplete_45_auc = get_auc(heatmap_data_dep_45)
make_heatmap(heatmap_data_dep_45, ax2, vlim, cbar_ax=cbar_ax, cmap=custom_cmap)

cbar_ax.tick_params(axis='both', length=0)
if SIMBA_METRIC == "zscore":
    cbar_ax.set_yticks((-1, 0, 1), labels=["-1", "0", "1"])
elif SIMBA_METRIC == "median":
    cbar_ax.set_yticks((-0.2, 0, 0.2), labels=["-20", "0", "20"])
elif SIMBA_METRIC == "raw":
    cbar_ax.set_yticks((0, 0.4))

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_heatmap_simba_deplete", FIGSFOLDER)

# %%
### 1C. Time Series Snips — Replete Condition
if SIMBA_METRIC == "zscore":
    ylims = (-0.5, 1)
    yscalebar=[0.3, 0.8]
elif SIMBA_METRIC == "median":
    ylims = (-0.08, 0.18)
    yscalebar=[0.05, 0.15]
elif SIMBA_METRIC == "raw":
    ylims = (0, 0.4)
    yscalebar=[0.1, 0.3]
else:
    ylims = calc_ylims
    yscalebar=[0.3, 0.8]
    
# Get animal-averaged snips for replete
snips_rep_10, snips_rep_45 = get_mean_snips(snips_to_plot, x_array, "replete")

f, ax = init_snips_figure()
plot_snips(snips_rep_10, snips_rep_45, ax, colors[0], colors[1], ylims, yscalebar=yscalebar, xscalebar=False)
ax.axhline(0, color="black", lw=1, ls="--", alpha=0.5, zorder=0)
ax.axvspan(5, 15, color="k", alpha=0.05, zorder=-10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_snips_simba_replete", FIGSFOLDER)

# %%
### 1D. Time Series Snips — Deplete Condition

# Get animal-averaged snips for deplete
snips_dep_10, snips_dep_45 = get_mean_snips(snips_to_plot, x_array, "deplete")

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3], ylims, xscalebar=True)  # Add scale bar for deplete condition
ax.axhline(0, color="black", lw=1, ls="--", alpha=0.5, zorder=0)
ax.axvspan(5, 15, color="k", alpha=0.05, zorder=-10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_snips_simba_deplete", FIGSFOLDER)


# %%
### 1E. AUC Summary — Bar Plot with Individual Data Points

def get_auc_and_sex_by_group(x_array, condition, infusiontype, simba_col="mean_simba"):
    grouped = (
        x_array
        .query("condition == @condition and infusiontype == @infusiontype")
        .groupby("id", sort=True)
        .agg(
            simba_col=(simba_col, "mean"),
            sex=("sex", "first"),
        )
    )
    auc_vals = grouped["simba_col"].to_numpy()
    sex_vals = grouped["sex"].fillna("Unknown").to_numpy()
    return auc_vals, sex_vals

if SIMBA_METRIC == "zscore":
    ylabel = "Appetitive Probability\n(Z-scored, all trials)"
elif SIMBA_METRIC == "median":
    ylabel = "Appetitive Probability\n(\u0394 from baseline)"
else:
    ylabel = "Appetitive Probability\n(Mean, all trials)"

# Organize AUCs by condition
replete_10_auc, replete_10_sex = get_auc_and_sex_by_group(x_array, "replete", "10NaCl", simba_col=simba_col)
replete_45_auc, replete_45_sex = get_auc_and_sex_by_group(x_array, "replete", "45NaCl", simba_col=simba_col)
deplete_10_auc, deplete_10_sex = get_auc_and_sex_by_group(x_array, "deplete", "10NaCl", simba_col=simba_col)
deplete_45_auc, deplete_45_sex = get_auc_and_sex_by_group(x_array, "deplete", "45NaCl", simba_col=simba_col)

replete_aucs = [replete_10_auc, replete_45_auc]
deplete_aucs = [deplete_10_auc, deplete_45_auc]
aucs = [replete_aucs, deplete_aucs]

sex_groups = [
    [replete_10_sex, replete_45_sex],
    [deplete_10_sex, deplete_45_sex],
]

f, ax = plot_auc_summary(
    aucs,
    colors,
    figsize=(2.2, 2.2),
    ylabel=ylabel,
    sex_groups=sex_groups,
    sex_markers={"M": "^", "F": "o"}
 )

if SAVE_FIGS:
    save_figure_atomic(f, "fig1_auc_simba_summary", FIGSFOLDER)


# %%
# 1E stats: one-sample tests against zero (no sex factor)
from stats_helpers import (
    one_sample_wilcoxon_table,
    prepare_mixedlm_auc_df,
    fit_mixedlm_with_fallback,
    omnibus_wald_table,
    posthoc_pairwise_auc,
    holm_matrix_from_posthoc,
)

# We evaluated both parametric and non-parametric one-sample approaches.
# Non-parametric testing was more appropriate for these AUC distributions,
# so we use Wilcoxon signed-rank tests for all groups for consistency.
group_data = {
    "Replete + 10NaCl": replete_aucs[0],
    "Replete + 45NaCl": replete_aucs[1],
    "Deplete + 10NaCl": deplete_aucs[0],
    "Deplete + 45NaCl": deplete_aucs[1],
}

stats_df = one_sample_wilcoxon_table(group_data)
print("Figure 1E — One-sample Wilcoxon signed-rank tests against zero (sex not included as a factor)")
display(stats_df)

# %%
# 1E omnibus model (ANOVA-like): condition within-subject, infusiontype/sex between-subject
# Build subject-by-condition dataset from averaged SIMBA metric
model_df = prepare_mixedlm_auc_df(x_array, value_col=simba_col)

print(f"Subjects included in omnibus model: {model_df['id'].nunique()}")
print(f"Rows (subject x condition): {len(model_df)}")

mixed_res, model_formula_used, model_fit_errors = fit_mixedlm_with_fallback(model_df)
if mixed_res is None:
    print("\nFigure 1E omnibus model could not be fit (all candidate models failed).")
    print("Model-fit errors:")
    for formula, err in model_fit_errors:
        print(f"  - {formula}: {err}")
else:
    print(f"\nFigure 1E omnibus model fitted with formula: {model_formula_used}")
    print("Fixed-effects omnibus tests (Wald):")
    try:
        display(omnibus_wald_table(mixed_res))
    except Exception:
        print("wald_test_terms not available; showing fixed-effects coefficient table instead.")
        display(mixed_res.summary().tables[1])

# %%
# 1E mixed ANOVA: condition (within) × infusiontype × sex (between)
# 3-way interaction (condition × infusiontype × sex) excluded — sex is included
# as a main effect and in 2-way interactions but the 3-way is pooled into error.
#
# Implemented via OLS decomposition (mathematically equivalent to standard mixed ANOVA):
#   Between-subjects effects  →  OLS on per-subject means (collapsed over condition)
#   Within-subjects effects   →  OLS on condition contrast (deplete − replete)

import statsmodels.formula.api as smf
from statsmodels.stats.anova import anova_lm
import numpy as np
import pandas as pd
from scipy import stats

# Pivot to wide format: one row per subject
wide_df = model_df.pivot_table(
    index=["id", "infusiontype", "sex"],
    columns="condition",
    values="auc",
).reset_index()
wide_df.columns.name = None
n_s = len(wide_df)

# Between-subjects partition: OLS on per-subject means
# Full factorial between factors (infusiontype × sex interaction retained)
wide_df["subj_mean"] = wide_df[["replete", "deplete"]].mean(axis=1)
bw_fit = smf.ols("subj_mean ~ C(infusiontype) * C(sex)", data=wide_df).fit()

# Within-subjects partition: OLS on condition contrast (deplete − replete)
# No 3-way: use additive model for within × between interactions
wide_df["cond_diff"] = wide_df["deplete"] - wide_df["replete"]
wi_fit = smf.ols("cond_diff ~ C(infusiontype) + C(sex)", data=wide_df).fit()

# Condition main effect F (computed manually from the within-subjects error)
mean_d = wide_df["cond_diff"].mean()
F_C = n_s * mean_d ** 2 / wi_fit.mse_resid
p_C = stats.f.sf(F_C, dfn=1, dfd=wi_fit.df_resid)

def _label(s):
    return (s.replace("C(infusiontype)", "infusiontype")
             .replace("C(sex)", "sex")
             .replace(":", " × "))

rows = []
for src, row in anova_lm(bw_fit, typ=2).iterrows():
    if src == "Residual":
        rows.append({"Source": "  Error (between-subjects)", "df": int(row["df"]),
                     "F": np.nan, "p": np.nan})
    else:
        rows.append({"Source": _label(src), "df": int(row["df"]),
                     "F": row["F"], "p": row["PR(>F)"]})

rows.append({"Source": "condition", "df": 1, "F": F_C, "p": p_C})

for src, row in anova_lm(wi_fit, typ=2).iterrows():
    if src == "Residual":
        rows.append({"Source": "  Error (within-subjects)", "df": int(row["df"]),
                     "F": np.nan, "p": np.nan})
    else:
        rows.append({"Source": "condition × " + _label(src), "df": int(row["df"]),
                     "F": row["F"], "p": row["PR(>F)"]})

aov_table = pd.DataFrame(rows).set_index("Source")

print("Mixed ANOVA  (condition: within | infusiontype, sex: between; 3-way interaction excluded)")
print(f"N = {n_s} subjects | Between-error df = {int(bw_fit.df_resid)} | "
      f"Within-error df = {int(wi_fit.df_resid)}\n")
display(aov_table.round(4))


# %%
# Export JASP-ready data for mixed ANOVA
# Saves both wide (recommended for repeated-measures setup in JASP) and long formats.

jasp_outdir = RESULTSFOLDER
jasp_outdir.mkdir(parents=True, exist_ok=True)

# Wide format: one row per subject, between factors as columns,
# repeated-measures levels as separate dependent-variable columns.
jasp_wide = (
    model_df
    .pivot_table(index=["id", "infusiontype", "sex"], columns="condition", values="auc")
    .reset_index()
)
jasp_wide.columns.name = None
jasp_wide = jasp_wide.rename(columns={
    "replete": "auc_replete",
    "deplete": "auc_deplete",
})

# Long format: one row per subject x condition
jasp_long = model_df[["id", "infusiontype", "sex", "condition", "auc"]].copy()

wide_path = jasp_outdir / "figure1_mixed_anova_jasp_wide.csv"
long_path = jasp_outdir / "figure1_mixed_anova_jasp_long.csv"

jasp_wide.to_csv(wide_path, index=False)
jasp_long.to_csv(long_path, index=False)

print("Saved JASP export files:")
print(f"  - {wide_path}")
print(f"  - {long_path}")
print("\nWide format columns:", list(jasp_wide.columns))
print("Long format columns:", list(jasp_long.columns))

display(jasp_wide.head())


# %%
# 1E posthoc pairwise tests across 4 groups (ignoring sex) with multiple-comparison correction
posthoc_results, groups = posthoc_pairwise_auc(x_array, value_col=simba_col)

print("Posthoc pairwise tests across 4 groups (sex ignored), Holm-corrected")
display(posthoc_results.sort_values("p_holm", na_position="last"))

# Compact 4x4 matrix view of Holm-adjusted p-values
p_matrix = holm_matrix_from_posthoc(posthoc_results, groups)
print("\nCompact matrix: Holm-adjusted p-values")
display(p_matrix)


# %%
### Correlation plots — Time moving across trials

def make_auc_data_per_trial(x_array, condition, infusiontype, simba_col):
    return (
        x_array
        .query("condition == @condition & infusiontype == @infusiontype")
        .groupby("trial")[simba_col]
        .mean()
        .values
    )
    
replete_10 = make_auc_data_per_trial(x_array, "replete", "10NaCl", simba_col)
replete_45 = make_auc_data_per_trial(x_array, "replete", "45NaCl", simba_col)
deplete_10 = make_auc_data_per_trial(x_array, "deplete", "10NaCl", simba_col)
deplete_45 = make_auc_data_per_trial(x_array, "deplete", "45NaCl", simba_col)

# f = make_correlation_plot_simba(replete_10, replete_45, colors[0], colors[1], yaxis=True)
# if SAVE_FIGS:
#     save_figure_atomic(f, "fig1_correlation_simba_replete", FIGSFOLDER)
    
# f = make_correlation_plot_simba(deplete_10, deplete_45, colors[2], colors[3])
# if SAVE_FIGS:
#     save_figure_atomic(f, "fig1_correlation_simba_deplete", FIGSFOLDER)

# %%
f, ax = make_correlation_plot_simba_1group(replete_10, colors[0], yaxis=True, simba_metric=SIMBA_METRIC)
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_simba_replete10", FIGSFOLDER)
    
f, ax = make_correlation_plot_simba_1group(replete_45, colors[1], simba_metric=SIMBA_METRIC)
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_simba_replete45", FIGSFOLDER)
    
f, ax = make_correlation_plot_simba_1group(deplete_10, colors[2], simba_metric=SIMBA_METRIC)
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_simba_deplete10", FIGSFOLDER)
    
f, ax = make_correlation_plot_simba_1group(deplete_45, colors[3], fit="sigmoid", simba_metric=SIMBA_METRIC)
if SAVE_FIGS:
    save_figure_atomic(f, "fig1_correlation_simba_deplete45", FIGSFOLDER)

# %%
### Model fits on time-moving by trial data with fit-quality checks
from model_fit_helpers import run_model_fit_comparison

fit_inputs = {
    "Replete + 10NaCl": replete_10,
    "Replete + 45NaCl": replete_45,
    "Deplete + 10NaCl": deplete_10,
    "Deplete + 45NaCl": deplete_45,
}

fit_results, sigmoid_params_table = run_model_fit_comparison(
    fit_inputs,
    models=("linear", "sigmoidal"),
)

print("Model fit results (AUC_simba by trial; linear + sigmoidal only) with quality checks:")
display(fit_results)

print("Sigmoidal fit parameters (AUC_simba by trial) with validity checks:")
display(sigmoid_params_table)

# %%
### Best valid model per condition (compact summary)
from model_fit_helpers import summarize_best_valid_model

best_model_summary = summarize_best_valid_model(fit_results)

print("Best valid model per condition (AICc-based):")
display(best_model_summary)

# %% [markdown]
# ## Euclidean distances

# %%
# prepare distance matrix for heatplots and MDS plot
matrix, series_labels, _, group_to_row_indices = make_metric_matrix(x_array, "simba_median_balance", GROUP_ORDER, GROUP_LABELS)

group_sizes = {GROUP_LABELS[group_key]: len(indices) for group_key, indices in group_to_row_indices.items()}
group_boundaries = np.cumsum([len(group_to_row_indices[group_key]) for group_key in GROUP_ORDER])

distances, group_distance_matrix = get_group_matrix_diffs(matrix, series_labels, group_to_row_indices)


# %%
# make euclidiean distance heatplots

fig, ax = make_euclidean_distance_heatmap_all_rats(distances, group_boundaries=group_boundaries)
if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_heatmap_euclidean_all_rats", FIGSFOLDER)
    
fig, ax, fig_cbar, ax_cbar = make_euclidean_distance_heatmap_averaged(group_distance_matrix)
ax_cbar.set_ylim([4,7])

if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_heatmap_euclidean_averaged", FIGSFOLDER)
    save_figure_atomic(fig_cbar, "fig1_heatmap_euclidean_averaged_cbar", FIGSFOLDER)

# %%
# make MDS plot for photometry data
coords = compute_mds_coordinates(distances)

fig, ax = make_mds_plot(coords, group_to_row_indices, reverse_axes="x")

if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_mds_plot", FIGSFOLDER)

# %%
### Figure 1 legend swatches (pie-style legend exports)

from matplotlib.patches import Patch

groups = ["", ""]

# Replete swatches (match archived spacing/placement exactly)
f, ax = plt.subplots(figsize=(0.35, 0.25), gridspec_kw={"left": 0.01, "right": 0.99})

legend_patches = []
for color, text in zip(colors[:2], groups):
    patch = Patch(color=color, label=text)
    legend_patches.append(patch)

ax.legend(
    handles=legend_patches,
    loc="center",
    fontsize=8,
    frameon=False,
    labelspacing=0.2,
    borderpad=0.05,
    )
ax.axis("off")

if SAVE_FIGS:
    f.savefig(FIGSFOLDER / "legend_pies_replete.pdf", dpi=600, transparent=True)

# Deplete swatches (match archived spacing/placement exactly)
f, ax = plt.subplots(figsize=(0.35, 0.25), gridspec_kw={"left": 0.01, "right": 0.99})

legend_patches = []
for color, text in zip(colors[2:], groups):
    patch = Patch(color=color, label=text)
    legend_patches.append(patch)

ax.legend(
    handles=legend_patches,
    loc="center",
    fontsize=8,
    frameon=False,
    labelspacing=0.2,
    borderpad=0.05,
    )
ax.axis("off")

if SAVE_FIGS:
    f.savefig(FIGSFOLDER / "legend_pies_deplete.pdf", dpi=600, transparent=True)

print("Saved legend swatch figures:")
print("  - legend_pies_replete.pdf")
print("  - legend_pies_deplete.pdf")

# %% [markdown]
# ## Organization
#
# This notebook generates **Figure 1 (Movement Analysis)** only. Each subsequent figure has its own dedicated notebook:
#
# - **figure_1_paper.ipynb**: Movement analysis (current)
# - **figure_2_paper.ipynb**: Photometry (dopamine) analysis  
# - **figure_3_paper.ipynb**: Neural-behavioral correlation
# - **figure_4_paper.ipynb**: Transition analysis
# - **figure_5_paper.ipynb**: Cluster analysis
#
# All notebooks share common settings and functions from:
# - `src/figure_config.py` — Colors, paths, parameters
# - `src/figure_plotting.py` — Data extraction and plotting functions
#
# This keeps each figure focused and manageable, while reducing code duplication.

# %%
# Configuration for Figure Saving
# ───────────────────────────────────────────────────────────────────────
# The SAVE_FIGS setting is loaded from figure_config.py
# Figures are saved in two formats:
#   - PDF for publication (vector format, smaller file size)
#   - PNG for presentations (raster format, high DPI for screen)
#
# All figures follow naming convention:
#   fig{number}_{description}.{pdf|png}
#
# Example:
#   fig1_heatmap_movement_replete.pdf
#   fig1_snips_movement_replete.png
# ───────────────────────────────────────────────────────────────────────

print(f"\nFigure saving is currently: {'ENABLED' if SAVE_FIGS else 'DISABLED'}")
print(f"Figure output folder: {FIGSFOLDER}")
if SAVE_FIGS:
    print("All generated figures will be saved in both PDF and PNG formats.")
else:
    print("To save figures, set SAVE_FIGS = True in src/figure_config.py")

# %%

# %% [markdown]
# ## Figure 1 (Bonus): Movement vs Angular Velocity Comparison
#
# Comparison of head rotation (angular velocity) with body movement to explore the relationship between these metrics across conditions.

# %%

# %%
### Per-Rat Time Series: Deplete + 45NaCl (4 metrics across trials)

n_rats = len(rats)
fig, axes = plt.subplots(n_rats, 4, figsize=(14, 2.5*n_rats))

# Handle case where there's only one rat (axes would not be 2D)
if n_rats == 1:
    axes = axes.reshape(1, -1)

# Column labels
col_labels = ['AUC Movement', 'Time Moving', 'AUC Angular Vel', 'Time Above Angvel']

# Add column titles at the top
for col, label in enumerate(col_labels):
    axes[0, col].annotate(label, xy=(0.5, 1.15), xycoords='axes fraction',
                         ha='center', fontsize=11, fontweight='bold')

# Plot each rat
for row, rat in enumerate(rats):
    rat_data = x_dep45[x_dep45['id'] == rat].reset_index(drop=True)
    rat_color = rat_colors[rat]
    trial_nums = range(len(rat_data))
    
    # Column 1: AUC Movement
    axes[row, 0].plot(trial_nums, rat_data['auc_movement'], 'o-', 
                     color=rat_color, markersize=4, linewidth=1, alpha=0.7)
    axes[row, 0].set_ylabel(f'Rat {rat}', fontsize=9, fontweight='bold', labelpad=10)
    axes[row, 0].grid(True, alpha=0.3)
    axes[row, 0].tick_params(labelsize=8)
    if row == n_rats - 1:
        axes[row, 0].set_xlabel('Trial #', fontsize=9)
    
    # Column 2: Time Moving
    axes[row, 1].plot(trial_nums, rat_data['time_moving'], 'o-', 
                     color=rat_color, markersize=4, linewidth=1, alpha=0.7)
    axes[row, 1].set_ylim([0, 1])
    axes[row, 1].grid(True, alpha=0.3)
    axes[row, 1].tick_params(labelsize=8)
    if row == n_rats - 1:
        axes[row, 1].set_xlabel('Trial #', fontsize=9)
    
    # Column 3: AUC Angular Velocity (if available)
    if 'auc_angvel' in rat_data.columns:
        axes[row, 2].plot(trial_nums, rat_data['auc_angvel'], 'o-', 
                         color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        axes[row, 2].grid(True, alpha=0.3)
        axes[row, 2].tick_params(labelsize=8)
        if row == n_rats - 1:
            axes[row, 2].set_xlabel('Trial #', fontsize=9)
    
    # Column 4: Time Above Angular Velocity Threshold (if available)
    if 'time_above_angvel_threshold' in rat_data.columns:
        axes[row, 3].plot(trial_nums, rat_data['time_above_angvel_threshold'], 'o-', 
                         color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        axes[row, 3].set_ylim([0, 1])
        axes[row, 3].grid(True, alpha=0.3)
        axes[row, 3].tick_params(labelsize=8)
        if row == n_rats - 1:
            axes[row, 3].set_xlabel('Trial #', fontsize=9)

fig.suptitle(f'Deplete + 45NaCl: Per-Rat Metrics Across Trials (n={len(x_dep45)} trials)', 
             fontsize=12, fontweight='bold', y=0.995)

plt.tight_layout()
if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_deplete45_perrat_timeseries", FIGSFOLDER)
plt.show()

# %%

# %%
### Per-Rat Angular Velocity Threshold Analysis: Deplete + 45NaCl

# Import the threshold function from assemble_all_data
from extract_behav_parameters import smooth_array

# Define different angular velocity thresholds to test
angvel_thresholds = [0.5, 1.0, 1.5, 2.0]
s, e = 50, 150  # Same bin range as used in assembly

# Prepare data: smooth angular velocity snips if not already smoothed
snips_angvel_smooth = smooth_array(snips_angvel, window_size=5)

# Pre-calculate time above threshold for all threshold values and all trials
threshold_data = {}
for thresh in angvel_thresholds:
    time_above = []
    for i in range(snips_angvel_smooth.shape[0]):
        snip = snips_angvel_smooth[i, s:e]
        proportion = len([x for x in snip if x > thresh]) / len(snip)
        time_above.append(proportion)
    threshold_data[thresh] = np.array(time_above)

# Create a dictionary of transition points by rat ID from fits_df
transition_points = {}
if fits_df is not None and len(fits_df) > 0:
    for _, row in fits_df.iterrows():
        transition_points[row['id']] = row['x0_orig']

# Create per-rat figure with one column per threshold
n_rats = len(rats)
fig, axes = plt.subplots(n_rats, len(angvel_thresholds), figsize=(12, 2.5*n_rats))

# Handle case where there's only one rat (axes would not be 2D)
if n_rats == 1:
    axes = axes.reshape(1, -1)

# Column labels with threshold values
col_labels = [f'Threshold = {t}°/frame' for t in angvel_thresholds]

# Add column titles at the top
for col, label in enumerate(col_labels):
    axes[0, col].annotate(label, xy=(0.5, 1.15), xycoords='axes fraction',
                         ha='center', fontsize=10, fontweight='bold')

# Plot each rat across all thresholds
for row, rat in enumerate(rats):
    rat_indices = x_dep45[x_dep45['id'] == rat].index.tolist()
    rat_color = rat_colors[rat]
    trial_nums = range(len(rat_indices))
    
    for col, thresh in enumerate(angvel_thresholds):
        ax = axes[row, col]
        rat_thresh_data = threshold_data[thresh][rat_indices]
        
        ax.plot(trial_nums, rat_thresh_data, 'o-', 
               color=rat_color, markersize=4, linewidth=1, alpha=0.7)
        ax.set_ylim([0, 1])
        ax.grid(True, alpha=0.3)
        ax.tick_params(labelsize=8)
        
        # Add transition point line if available for this rat
        if rat in transition_points:
            x0 = transition_points[rat]
            ax.axvline(x=x0, color='red', linestyle='--', linewidth=1.5, alpha=0.7, label=f'x0={x0:.1f}')
            ax.legend(fontsize=7, loc='upper right')
        
        # Add rat label on first column
        if col == 0:
            ax.set_ylabel(f'Rat {rat}', fontsize=9, fontweight='bold', labelpad=10)
        
        # Add x-axis label on bottom row
        if row == n_rats - 1:
            ax.set_xlabel('Trial #', fontsize=9)

fig.suptitle(f'Deplete + 45NaCl: Per-Rat Angular Velocity Threshold Analysis (n={len(x_dep45)} trials)', 
             fontsize=12, fontweight='bold', y=0.995)

plt.tight_layout()
if SAVE_FIGS:
    save_figure_atomic(fig, "fig1_deplete45_perrat_angvel_thresholds", FIGSFOLDER)
plt.show()

print(f"Angular velocity threshold analysis completed.")
print(f"Thresholds tested: {angvel_thresholds} degrees/frame")
print(f"Data window: bins {s}-{e}")
print(f"Number of rats: {n_rats}")
print(f"\nTransition points available for:")
for rat in rats:
    if rat in transition_points:
        print(f"  Rat {rat}: x0_orig = {transition_points[rat]:.2f} trials")
    else:
        print(f"  Rat {rat}: no transition fit available")

# %%
snips_simba_app = snips_simba[x_array.query("condition == 'deplete' and infusiontype == '10NaCl'").index]
sns.heatmap(snips_simba_app, cmap='viridis')

# %%
snips_simba_switch = snips_simba[x_array.query("condition == 'deplete' and infusiontype == '45NaCl'").index]
sns.heatmap(snips_simba_switch, cmap='viridis')

# %%
snips_simba_replete = snips_simba[x_array.query("condition == 'replete'").index]
sns.heatmap(snips_simba_replete, cmap='viridis')

# %%
for id in x_array['id'].unique():
    print(f"Rat {id}:")
    rat_snips = snips_simba[x_array.query("id == @id").index]
    sns.heatmap(rat_snips, cmap='viridis')
    plt.title(f"Rat {id} - SIMBA Snips")
    plt.show()

# %%

# %% [markdown]
# ## Per-snip cross-correlation (best lag + r)
#
# Compute cross-correlations between matching snips from two arrays (one row per snip), and return a dataframe with:
# - `best_lag`: lag (in bins) where correlation is strongest
# - `r`: corresponding Pearson correlation value
#
# Default lag search is `-30` to `+30` bins (e.g., with 0.1 s bins this is `-3` to `+3` s).

# %%
import numpy as np
import pandas as pd


def _lagged_pearson(x, y, lag, min_overlap=10):
    """Pearson r between 1D vectors at a given lag.

    Positive lag means y is shifted to the right relative to x.
    """
    if lag > 0:
        x_use = x[:-lag]
        y_use = y[lag:]
    elif lag < 0:
        k = -lag
        x_use = x[k:]
        y_use = y[:-k]
    else:
        x_use = x
        y_use = y

    # Keep only finite overlap and guard against tiny/constant segments.
    valid = np.isfinite(x_use) & np.isfinite(y_use)
    x_use = x_use[valid]
    y_use = y_use[valid]

    if x_use.size < min_overlap:
        return np.nan
    if np.std(x_use) == 0 or np.std(y_use) == 0:
        return np.nan

    return float(np.corrcoef(x_use, y_use)[0, 1])


def crosscorr_best_lag_df(
    snips_x,
    snips_y,
    lag_min=-30,
    lag_max=30,
    min_overlap=10,
    select_by="max_abs",
):
    """Return per-snip best lag and r for two arrays shaped (n_snips, n_bins)."""
    x = np.asarray(snips_x, dtype=float)
    y = np.asarray(snips_y, dtype=float)

    if x.ndim != 2 or y.ndim != 2:
        raise ValueError("Both inputs must be 2D arrays with shape (n_snips, n_bins).")
    if x.shape != y.shape:
        raise ValueError(f"Shape mismatch: snips_x {x.shape} vs snips_y {y.shape}.")
    if not (isinstance(lag_min, int) and isinstance(lag_max, int) and lag_min <= lag_max):
        raise ValueError("lag_min and lag_max must be integers with lag_min <= lag_max.")
    if min_overlap < 3:
        raise ValueError("min_overlap must be >= 3.")
    if select_by not in {"max_abs", "max_pos"}:
        raise ValueError("select_by must be 'max_abs' or 'max_pos'.")

    n_snips, n_bins = x.shape
    lags = np.arange(lag_min, lag_max + 1)

    if np.max(np.abs(lags)) >= n_bins:
        raise ValueError(
            f"Lag range too wide for snip length ({n_bins} bins). "
            f"Max allowed absolute lag is {n_bins - 1}."
        )

    out_lag = np.full(n_snips, np.nan)
    out_r = np.full(n_snips, np.nan)

    for i in range(n_snips):
        rs = np.array([_lagged_pearson(x[i], y[i], lag, min_overlap=min_overlap) for lag in lags], dtype=float)
        valid = np.isfinite(rs)

        if not np.any(valid):
            continue

        if select_by == "max_abs":
            best_local_idx = np.nanargmax(np.abs(rs))
        else:
            best_local_idx = np.nanargmax(rs)

        out_lag[i] = lags[best_local_idx]
        out_r[i] = rs[best_local_idx]

    df_best = pd.DataFrame({
        "best_lag": out_lag,
        "r": out_r,
    })
    df_best["best_lag"] = df_best["best_lag"].astype("Int64")
    return df_best


# ---- Run on your arrays (edit lag_min/lag_max as needed) ----
lag_min, lag_max = -30, 30
bin_size_s = 0.1  # change if your bins are not 100 ms

# Expected variables: snips_photo, snips_simba_shifted_baseline
if "snips_photo" not in globals() or "snips_simba_shifted_baseline" not in globals():
    raise NameError(
        "Expected variables 'snips_photo' and 'snips_simba_shifted_baseline' in the notebook namespace."
    )

xcorr_df = crosscorr_best_lag_df(
    snips_x=snips_photo,
    snips_y=snips_simba_shifted_baseline,
    lag_min=lag_min,
    lag_max=lag_max,
    min_overlap=10,
    select_by="max_abs",  # use 'max_pos' if you only want most positive correlation
)

print(f"Result shape: {xcorr_df.shape}")
print(
    f"Lag window: [{lag_min}, {lag_max}] bins "
    f"(~[{lag_min * bin_size_s:.1f}, {lag_max * bin_size_s:.1f}] s at {bin_size_s:.3f} s/bin)"
)
print(f"Rows with valid best lag/r: {xcorr_df['r'].notna().sum()} / {len(xcorr_df)}")

xcorr_df.head()
