# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.2
#   kernelspec:
#     display_name: default
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Paper Figures: Figure 2 - Photometry (Dopamine) Analysis
#
# This notebook generates publication-ready figures for photometry data (dopamine responses) using data assembled by `src/assemble_all_data.py`.
#
# **Figure 2: Photometry Analysis** — Neural responses showing dopamine heatmaps and summary plots for replete and deplete conditions across sodium concentrations.

# %%
# %load_ext autoreload
# %autoreload 2

import pathlib
from pathlib import Path
import sys
sys.path.insert(0, str(Path("../src").resolve()))
from pickle_compat import enable_dill_pathlib_compat
enable_dill_pathlib_compat()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import dill

from trompy import save_figure_atomic

from distance_matrix import (make_metric_matrix, get_group_matrix_diffs,
                             GROUP_ORDER, GROUP_LABELS,
                             compute_mds_coordinates
)

from figure_config import (
    configure_matplotlib, COLORS, HEATMAP_CMAP_DIV, 
    DATAFOLDER, RESULTSFOLDER, FIGSFOLDER,
    HEATMAP_VLIM_PHOTO, YLIMS_PHOTO,
    PHOTO_SMOOTH_WINDOW, SAVE_FIGS
)
from figure_plotting import (
    smooth_array, get_heatmap_data, get_mean_snips, get_auc,
    init_heatmap_figure, init_snips_figure, make_heatmap,
    plot_snips, plot_auc_summary, print_auc_stats,
    scale_vlim_to_data, calculate_ylims, make_correlation_plot_da,
    make_correlation_plot_da_1group, make_mds_plot,
    make_euclidean_distance_heatmap_all_rats, make_euclidean_distance_heatmap_averaged
)

# Configure matplotlib
configure_matplotlib()
colors = COLORS  # Use shared color palette
custom_cmap = HEATMAP_CMAP_DIV  # Use shared colormap

SAVE_FIGS = True  # Set to True to save figures, False to display only

# %% [markdown]
# ## Load Assembled Data
#
# Load the complete dataset from the pickle file generated by the assembly script.

# %%
assembled_data_path = DATAFOLDER / "assembled_data.pickle"

with open(assembled_data_path, "rb") as f:
    data = dill.load(f)

# Extract main components
x_array = data["x_array"]
snips_photo = data["snips_photo"]
params = data.get("params", {})
metadata = data.get("metadata", {})

print(f"Loaded assembled data from {assembled_data_path}")
print(f"\nData structure:")
print(f"  - x_array shape: {x_array.shape}")
print(f"  - snips_photo shape: {snips_photo.shape}")
print(f"  - x_array columns: {x_array.columns.tolist()}")
print(f"  - Number of trials: {len(x_array)}") 

# Check data processing metadata
print(f"\nData processing metadata:")
if metadata:
    print(f"  Behaviour metric: {metadata.get('behav_metric', 'unknown')}")
    print(f"  Behaviour smoothed: {metadata.get('behav_smoothed', False)}")
    print(f"  Behaviour z-scored: {metadata.get('behav_zscored', False)}")
    print(f"  Photometry smoothed: {metadata.get('photo_smoothed', False)}")
    print(f"  Photometry z-scored: {metadata.get('photo_zscored', False)}")
else:
    print(f"  No metadata found; assuming standard processing")

# Store metadata flags for use during plotting
photo_already_smoothed = metadata.get('photo_smoothed', False)

# %% [markdown]
# ## Figure 2: Photometry Analysis — Dopamine Responses
#
# Analysis of neural dopamine responses showing heatmaps, snip time series, and summary AUC metrics across replete and deplete sodium conditions, separated by infusion type (10NaCl vs 45NaCl).

# %% [markdown]
# ### Heatmaps

# %%
# Photometry (dopamine) data is NOT smoothed during assembly
# Do not apply any smoothing to maintain signal fidelity
snips_photo_smooth = snips_photo  # Use as-is, unsmoothed
print(f"Using unsmoothed photometry data (photometry is NOT smoothed during assembly)")

# Parameters for visualization
# Use dynamic scaling based on actual data instead of static limits
vlim = scale_vlim_to_data(snips_photo_smooth, percentile=80)
print("Based on data, vlim are:", vlim)
vlim = (-1, 1)  # Uncomment to override auto scaling with hardcoded values


# %%
### 2A. Heatmaps — Replete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Replete + 10NaCl
heatmap_data_rep_10 = get_heatmap_data(snips_photo_smooth, x_array, "replete", "10NaCl")
replete_10_auc = get_auc(heatmap_data_rep_10)
make_heatmap(heatmap_data_rep_10, ax1, vlim, inf_bar=True, cmap=custom_cmap)

# Replete + 45NaCl
heatmap_data_rep_45 = get_heatmap_data(snips_photo_smooth, x_array, "replete", "45NaCl")
replete_45_auc = get_auc(heatmap_data_rep_45)
make_heatmap(heatmap_data_rep_45, ax2, vlim, cmap=custom_cmap, cbar_ax=cbar_ax)

if SAVE_FIGS:
    save_figure_atomic(f, "fig2_heatmap_dopamine_replete", FIGSFOLDER)


# %%
### 2B. Heatmaps — Deplete Condition

f, ax1, ax2, cbar_ax = init_heatmap_figure()

# Deplete + 10NaCl
heatmap_data_dep_10 = get_heatmap_data(snips_photo_smooth, x_array, "deplete", "10NaCl")
deplete_10_auc = get_auc(heatmap_data_dep_10)
make_heatmap(heatmap_data_dep_10, ax1, vlim, cmap=custom_cmap, inf_bar=True)

# Deplete + 45NaCl
heatmap_data_dep_45 = get_heatmap_data(snips_photo_smooth, x_array, "deplete", "45NaCl")
deplete_45_auc = get_auc(heatmap_data_dep_45)
make_heatmap(heatmap_data_dep_45, ax2, vlim, cmap=custom_cmap, cbar_ax=cbar_ax)

if SAVE_FIGS:
    save_figure_atomic(f, "fig2_heatmap_dopamine_deplete", FIGSFOLDER)


# %% [markdown]
# ### Line plots

# %%

ylims = calculate_ylims(snips_photo_smooth)  # Calculate ylims based on data
print("Based on data, ylims are:", ylims)
ylims = (-0.6, 3)  # snips plot limits

# %%
### 2C. Time Series Snips — Replete Condition

# Get animal-averaged snips for replete
snips_rep_10, snips_rep_45 = get_mean_snips(snips_photo_smooth, x_array, "replete")

f, ax = init_snips_figure()
plot_snips(snips_rep_10, snips_rep_45, ax, colors[0], colors[1], ylims)
ax.axvspan(5, 15, color="k", alpha=0.05, zorder=-10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig2_snips_dopamine_replete", FIGSFOLDER)


# %%
### 2D. Time Series Snips — Deplete Condition

# Get animal-averaged snips for deplete
snips_dep_10, snips_dep_45 = get_mean_snips(snips_photo_smooth, x_array, "deplete")

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3], ylims, yscalebar=(1,2), xscalebar=True)
ax.axvspan(5, 15, color="k", alpha=0.05, zorder=-10)

if SAVE_FIGS:
    save_figure_atomic(f, "fig2_snips_dopamine_deplete", FIGSFOLDER)


# %% [markdown]
# ### AUC bar graph

# %%
### 2E. AUC Summary — Bar Plot with Individual Data Points

# Organize AUCs by condition (raw values remain unchanged)
replete_aucs = [get_auc(snips_rep_10), get_auc(snips_rep_45)]
deplete_aucs = [get_auc(snips_dep_10), get_auc(snips_dep_45)]
aucs = [replete_aucs, deplete_aucs]

# # Display-only scaling so axis values are in per-second units at 10 Hz
AUC_DISPLAY_SCALE = 10.0
replete_aucs_display = [arr / AUC_DISPLAY_SCALE for arr in replete_aucs]
deplete_aucs_display = [arr / AUC_DISPLAY_SCALE for arr in deplete_aucs]
aucs_display = [replete_aucs_display, deplete_aucs_display]

# Build sex labels in the same id order used for animal-averaged snips
def get_group_sexes(x_array, condition, infusiontype):
    ids = x_array.query("condition == @condition & infusiontype == @infusiontype").id.unique()
    sex_by_id = (
        x_array[["id", "sex"]]
        .dropna()
        .drop_duplicates(subset=["id"])
        .set_index("id")["sex"]
    )
    return np.array([sex_by_id.get(rat_id, "Unknown") for rat_id in ids])

sex_groups = [
    [
        get_group_sexes(x_array, "replete", "10NaCl"),
        get_group_sexes(x_array, "replete", "45NaCl"),
    ],
    [
        get_group_sexes(x_array, "deplete", "10NaCl"),
        get_group_sexes(x_array, "deplete", "45NaCl"),
    ],
]

f, ax = plot_auc_summary(
    aucs_display,
    colors,
    ylabel="Dopamine (AUC)",
    figsize=(2.2, 2.2),
    sex_groups=sex_groups,
    sex_markers={"M": "^", "F": "o"},
)

ax.set_ylim(-10, 20)

if SAVE_FIGS:
    save_figure_atomic(f, "fig2_auc_dopamine_summary", FIGSFOLDER)

# Print display-scaled summary statistics
auc_labels = [
    f"Replete + 10NaCl (n={len(snips_rep_10)})",
    f"Replete + 45NaCl (n={len(snips_rep_45)})",
    f"Deplete + 10NaCl (n={len(snips_dep_10)})",
    f"Deplete + 45NaCl (n={len(snips_dep_45)})"
]
auc_arrays_display = [
    replete_aucs_display[0],
    replete_aucs_display[1],
    deplete_aucs_display[0],
    deplete_aucs_display[1],
]
print_auc_stats(
    auc_arrays_display,
    auc_labels,
    title="Figure 2 - Dopamine Summary Statistics (display-scaled to per-second units)",
)

# %%
# 2E stats for dopamine AUCs (using shared helpers, display-scaled only)
from stats_helpers import (
    one_sample_wilcoxon_table,
    prepare_mixedlm_auc_df,
    fit_mixedlm_with_fallback,
    omnibus_wald_table,
    posthoc_pairwise_auc,
    holm_matrix_from_posthoc,
)

auc_display_scale = globals().get("AUC_DISPLAY_SCALE", 10.0)
x_array_display = x_array.assign(auc_snips=x_array["auc_snips"] / auc_display_scale)

# 1) One-sample tests against zero for each group (sex not included as factor)
group_data = {
    "Replete + 10NaCl": replete_aucs[0] / auc_display_scale,
    "Replete + 45NaCl": replete_aucs[1] / auc_display_scale,
    "Deplete + 10NaCl": deplete_aucs[0] / auc_display_scale,
    "Deplete + 45NaCl": deplete_aucs[1] / auc_display_scale,
}
dopamine_one_sample_df = one_sample_wilcoxon_table(group_data)
print(f"Figure 2E - One-sample Wilcoxon signed-rank tests against zero (display-scaled by 1/{auc_display_scale:g})")
display(dopamine_one_sample_df)

# 2) Omnibus model: condition within-subject, infusiontype and sex between-subject
dopamine_model_df = prepare_mixedlm_auc_df(x_array_display)
print(f"\nSubjects included in omnibus model: {dopamine_model_df['id'].nunique()}")
print(f"Rows (subject x condition): {len(dopamine_model_df)}")

dopamine_mixed_res, dopamine_formula_used, dopamine_fit_errors = fit_mixedlm_with_fallback(dopamine_model_df)
if dopamine_mixed_res is None:
    print("\nFigure 2E omnibus model could not be fit (all candidate models failed).")
    print("Model-fit errors:")
    for formula, method, err in dopamine_fit_errors:
        print(f"  - {formula} [{method}]: {err}")
else:
    print(f"\nFigure 2E omnibus model fitted with formula: {dopamine_formula_used}")
    print("Figure 2E omnibus fixed-effects tests (Wald):")
    try:
        display(omnibus_wald_table(dopamine_mixed_res))
    except Exception:
        print("wald_test_terms not available; showing fixed-effects coefficient table instead.")
        display(dopamine_mixed_res.summary().tables[1])

# 3) Posthoc pairwise tests across 4 groups (ignoring sex), Holm-corrected
dopamine_posthoc_results, dopamine_groups = posthoc_pairwise_auc(x_array_display)
print(f"\nFigure 2E posthoc pairwise tests across 4 groups (sex ignored), Holm-corrected (display-scaled by 1/{auc_display_scale:g})")
display(dopamine_posthoc_results.sort_values("p_holm", na_position="last"))

# Compact matrix view of Holm-adjusted p-values
dopamine_p_matrix = holm_matrix_from_posthoc(dopamine_posthoc_results, dopamine_groups)
print("\nFigure 2E compact matrix: Holm-adjusted p-values")
display(dopamine_p_matrix)

# %%
# 2E mixed ANOVA: condition (within) x infusiontype x sex (between)
# 3-way interaction excluded; sex main effect and relevant 2-way interactions retained.

import statsmodels.formula.api as smf
from statsmodels.stats.anova import anova_lm
import numpy as np
import pandas as pd
from scipy import stats

# Rebuild dopamine_model_df if needed (same display scaling as omnibus cell)
if "dopamine_model_df" not in globals():
    auc_display_scale = globals().get("AUC_DISPLAY_SCALE", 10.0)
    x_array_display = x_array.assign(auc_snips=x_array["auc_snips"] / auc_display_scale)
    dopamine_model_df = prepare_mixedlm_auc_df(x_array_display)

wide_df = dopamine_model_df.pivot_table(
    index=["id", "infusiontype", "sex"],
    columns="condition",
    values="auc",
).reset_index()
wide_df.columns.name = None
n_s = len(wide_df)

# Between-subjects model: infusiontype + sex + infusiontype:sex
wide_df["subj_mean"] = wide_df[["replete", "deplete"]].mean(axis=1)
bw_fit = smf.ols("subj_mean ~ C(infusiontype) * C(sex)", data=wide_df).fit()

# Within-subjects contrast model: condition effects and 2-way interactions only
wide_df["cond_diff"] = wide_df["deplete"] - wide_df["replete"]
wi_fit = smf.ols("cond_diff ~ C(infusiontype) + C(sex)", data=wide_df).fit()

mean_d = wide_df["cond_diff"].mean()
F_C = n_s * mean_d ** 2 / wi_fit.mse_resid
p_C = stats.f.sf(F_C, dfn=1, dfd=wi_fit.df_resid)

def _label(s):
    return (s.replace("C(infusiontype)", "infusiontype")
             .replace("C(sex)", "sex")
             .replace(":", " x "))

rows = []
for src, row in anova_lm(bw_fit, typ=2).iterrows():
    if src == "Residual":
        rows.append({"Source": "Error (between-subjects)", "df": int(row["df"]), "F": np.nan, "p": np.nan})
    else:
        rows.append({"Source": _label(src), "df": int(row["df"]), "F": row["F"], "p": row["PR(>F)"]})

rows.append({"Source": "condition", "df": 1, "F": F_C, "p": p_C})

for src, row in anova_lm(wi_fit, typ=2).iterrows():
    if src == "Residual":
        rows.append({"Source": "Error (within-subjects)", "df": int(row["df"]), "F": np.nan, "p": np.nan})
    else:
        rows.append({"Source": "condition x " + _label(src), "df": int(row["df"]), "F": row["F"], "p": row["PR(>F)"]})

dopamine_aov_table = pd.DataFrame(rows).set_index("Source")

print("Figure 2E mixed ANOVA (condition: within | infusiontype, sex: between; 3-way excluded)")
print(f"N = {n_s} subjects | Between-error df = {int(bw_fit.df_resid)} | Within-error df = {int(wi_fit.df_resid)}")
display(dopamine_aov_table.round(4))

# %%
# Export JASP-ready data for Figure 2 mixed ANOVA
# Saves both wide and long formats.

# Rebuild dopamine_model_df if needed (same display scaling as omnibus cell)
if "dopamine_model_df" not in globals():
    auc_display_scale = globals().get("AUC_DISPLAY_SCALE", 10.0)
    x_array_display = x_array.assign(auc_snips=x_array["auc_snips"] / auc_display_scale)
    dopamine_model_df = prepare_mixedlm_auc_df(x_array_display)

jasp_outdir = RESULTSFOLDER
jasp_outdir.mkdir(parents=True, exist_ok=True)

jasp_wide = (
    dopamine_model_df
    .pivot_table(index=["id", "infusiontype", "sex"], columns="condition", values="auc")
    .reset_index()
)
jasp_wide.columns.name = None
jasp_wide = jasp_wide.rename(columns={
    "replete": "auc_replete",
    "deplete": "auc_deplete",
})

jasp_long = dopamine_model_df[["id", "infusiontype", "sex", "condition", "auc"]].copy()

wide_path = jasp_outdir / "figure2_mixed_anova_jasp_wide.csv"
long_path = jasp_outdir / "figure2_mixed_anova_jasp_long.csv"

jasp_wide.to_csv(wide_path, index=False)
jasp_long.to_csv(long_path, index=False)

print("Saved JASP export files:")
print(f"  - {wide_path}")
print(f"  - {long_path}")
print("\nWide format columns:", list(jasp_wide.columns))
print("Long format columns:", list(jasp_long.columns))

display(jasp_wide.head())


# %% [markdown]
# ### Correlation plots

# %%
def make_auc_data_per_trial(x_array, condition, infusiontype):
    
    return (
        x_array
        .query("condition == @condition & infusiontype == @infusiontype")
        .groupby("trial")
        .auc_snips
        .mean()
        .values
    )
    
replete_10 = make_auc_data_per_trial(x_array, "replete", "10NaCl")
replete_45 = make_auc_data_per_trial(x_array, "replete", "45NaCl")
deplete_10 = make_auc_data_per_trial(x_array, "deplete", "10NaCl")
deplete_45 = make_auc_data_per_trial(x_array, "deplete", "45NaCl")

f = make_correlation_plot_da(replete_10, replete_45, colors[0], colors[1], yaxis=True)
if SAVE_FIGS:
    save_figure_atomic(f, "fig2_correlation_da_replete", FIGSFOLDER)
    
f = make_correlation_plot_da(deplete_10, deplete_45, colors[2], colors[3])
if SAVE_FIGS:
    save_figure_atomic(f, "fig2_correlation_da_deplete", FIGSFOLDER)

# %%
f, ax = make_correlation_plot_da_1group(replete_10, colors[0], yaxis=True)
if SAVE_FIGS:
    save_figure_atomic(f, "fig2_correlation_da_replete10", FIGSFOLDER)

f, ax = make_correlation_plot_da_1group(replete_45, colors[1])
if SAVE_FIGS:
    save_figure_atomic(f, "fig2_correlation_da_replete45", FIGSFOLDER)

f, ax = make_correlation_plot_da_1group(deplete_10, colors[2])
if SAVE_FIGS:    
    save_figure_atomic(f, "fig2_correlation_da_deplete10", FIGSFOLDER)

f, ax = make_correlation_plot_da_1group(deplete_45, colors[3], fit="sigmoid")
if SAVE_FIGS:
    save_figure_atomic(f, "fig2_correlation_da_deplete45", FIGSFOLDER)

# %%
# 2F. Model fits on AUC-by-trial data with fit-quality checks
from model_fit_helpers import run_model_fit_comparison

fit_inputs = {
    "Replete + 10NaCl": replete_10,
    "Replete + 45NaCl": replete_45,
    "Deplete + 10NaCl": deplete_10,
    "Deplete + 45NaCl": deplete_45,
}

fit_results, sigmoid_diagnostics_table = run_model_fit_comparison(fit_inputs)

print("Model fit results (AUC by trial) with quality checks:")
display(fit_results)

# %%
# 2G. Sigmoidal fit parameters and validity checks by condition
sigmoid_params_table = sigmoid_diagnostics_table[[
    "Condition", "L", "k", "x0", "b",
    "Sigmoid_valid", "Sigmoid_flags",
    "x0_interior", "k_plausible", "ci_finite", "asymptotes_covered",
]].copy()

print("Sigmoidal fit parameters (AUC by trial) with validity checks:")
display(sigmoid_params_table)

# %%
# 2H. Best valid model per condition (compact summary)
from model_fit_helpers import summarize_best_valid_model

best_model_summary = summarize_best_valid_model(fit_results)

print("Best valid model per condition (AICc-based):")
display(best_model_summary)

# %% [markdown]
# ### Euclidean distances

# %%
x_array.columns

# %%
# prepare distance matrix for heatplots and MDS plot
matrix, series_labels, _, group_to_row_indices = make_metric_matrix(x_array, "auc_snips", GROUP_ORDER, GROUP_LABELS)

group_sizes = {GROUP_LABELS[group_key]: len(indices) for group_key, indices in group_to_row_indices.items()}
group_boundaries = np.cumsum([len(group_to_row_indices[group_key]) for group_key in GROUP_ORDER])

distances, group_distance_matrix = get_group_matrix_diffs(matrix, series_labels, group_to_row_indices)



# %%
# make euclidiean distance heatplots

fig, ax = make_euclidean_distance_heatmap_all_rats(distances, group_boundaries=group_boundaries)
if SAVE_FIGS:
    save_figure_atomic(fig, "fig2_heatmap_euclidean_all_rats", FIGSFOLDER)
    
fig, ax, fig_cbar, ax_cbar = make_euclidean_distance_heatmap_averaged(group_distance_matrix)
ax_cbar.set_ylim([60, 100])
ax_cbar.set_yticks([60, 80, 100], labels=["6", "8", "10"])

if SAVE_FIGS:
    save_figure_atomic(fig, "fig2_heatmap_euclidean_averaged", FIGSFOLDER)
    save_figure_atomic(fig_cbar, "fig2_heatmap_euclidean_averaged_cbar", FIGSFOLDER)

# %%
# make MDS plot for photometry data
coords = compute_mds_coordinates(distances)

fig, ax = make_mds_plot(coords, group_to_row_indices, reverse_axes="y")

if SAVE_FIGS:
    save_figure_atomic(fig, "fig2_mds_plot", FIGSFOLDER)

# %% [markdown]
# ### Supplemental fig with different epochs (S3?)

# %%
x_array["auc_early"] = np.trapezoid(snips_photo[:,50:80], x=np.arange(50, 80))
x_array["auc_late"] = np.trapezoid(snips_photo[:,80:150], x=np.arange(80, 150))

def make_auc_data_per_trial_early(x_array, condition, infusiontype):
    
    return (
        x_array
        .query("condition == @condition & infusiontype == @infusiontype")
        .groupby("trial")
        .auc_early
        .mean()
        .values
    )
    
def make_auc_data_per_trial_late(x_array, condition, infusiontype):
    
    return (
        x_array
        .query("condition == @condition & infusiontype == @infusiontype")
        .groupby("trial")
        .auc_late
        .mean()
        .values
    )


# %%

# make line plots with shaded area showing epochs
## epoch 1 - FULL epoch
epoch = [5, 15]

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3],
           ylims, fill_epoch=epoch, yscalebar=(1,2), xscalebar=True)

if SAVE_FIGS:
    save_figure_atomic(f, "figS3_snips_deplete_epoch1", FIGSFOLDER)

ylim = (-60, 190)  # AUC plot limits for full epoch
f, ax = make_correlation_plot_da_1group(deplete_10, colors[2], yaxis=True, print_stats=False, ylim=ylim)
if SAVE_FIGS:    
    save_figure_atomic(f, "figS3_correlation_da_deplete10_epoch1", FIGSFOLDER)

f, ax = make_correlation_plot_da_1group(deplete_45, colors[3], fit="sigmoid", print_stats=False, ylim=ylim)
if SAVE_FIGS:
    save_figure_atomic(f, "figS3_correlation_da_deplete45_epoch1", FIGSFOLDER)
    
## epoch 2 - EARLY epoch
epoch = [5, 8]

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3],
           ylims, fill_epoch=epoch, yscalebar=(1,2), xscalebar=True)

if SAVE_FIGS:
    save_figure_atomic(f, "figS3_snips_deplete_epoch2", FIGSFOLDER)
    
deplete_10_auc_epoch2 = make_auc_data_per_trial_early(x_array, "deplete", "10NaCl")
deplete_45_auc_epoch2 = make_auc_data_per_trial_early(x_array, "deplete", "45NaCl")

ylim = (-20, 100)

f, ax = make_correlation_plot_da_1group(deplete_10_auc_epoch2, colors[2], yaxis=True, print_stats=False, ylim=ylim)
if SAVE_FIGS:    
    save_figure_atomic(f, "figS3_correlation_da_deplete10_epoch2", FIGSFOLDER)

f, ax = make_correlation_plot_da_1group(deplete_45_auc_epoch2, colors[3], fit="sigmoid", print_stats=False, ylim=ylim)
if SAVE_FIGS:
    save_figure_atomic(f, "figS3_correlation_da_deplete45_epoch2", FIGSFOLDER)

## epoch 3 - LATE epoch
epoch = [8, 14.9]

f, ax = init_snips_figure()
plot_snips(snips_dep_10, snips_dep_45, ax, colors[2], colors[3],
           ylims, fill_epoch=epoch, yscalebar=(1,2), xscalebar=True)

if SAVE_FIGS:
    save_figure_atomic(f, "figS3_snips_deplete_epoch3", FIGSFOLDER)
    
deplete_10_auc_epoch3 = make_auc_data_per_trial_late(x_array, "deplete", "10NaCl")
deplete_45_auc_epoch3 = make_auc_data_per_trial_late(x_array, "deplete", "45NaCl")

ylim = (-60, 190)

f, ax = make_correlation_plot_da_1group(deplete_10_auc_epoch3, colors[2], yaxis=True, print_stats=False, ylim=ylim)
if SAVE_FIGS:    
    save_figure_atomic(f, "figS3_correlation_da_deplete10_epoch3", FIGSFOLDER)
    
f, ax = make_correlation_plot_da_1group(deplete_45_auc_epoch3, colors[3], fit="sigmoid", print_stats=False, ylim=ylim)
if SAVE_FIGS:
    save_figure_atomic(f, "figS3_correlation_da_deplete45_epoch3", FIGSFOLDER)


# %% [markdown]
# ## Organization
#
# This notebook generates **Figure 2 (Photometry Analysis)** only. Each figure has its own dedicated notebook:
#
# - **figure_1_paper.ipynb**: Movement analysis
# - **figure_2_paper.ipynb**: Photometry (dopamine) analysis (current)
# - **figure_3_paper.ipynb**: Neural-behavioral correlation
# - **figure_4_paper.ipynb**: Transition analysis
# - **figure_5_paper.ipynb**: Cluster analysis
#
# All notebooks share common settings and functions from:
# - `src/figure_config.py` — Colors, paths, parameters
# - `src/figure_plotting.py` — Data extraction and plotting functions
#
# This keeps each figure focused and manageable, while reducing code duplication.

# %%
# Configuration for Figure Saving
# ───────────────────────────────────────────────────────────────────────
# The SAVE_FIGS setting is loaded from figure_config.py
# Figures are saved in two formats:
#   - PDF for publication (vector format, smaller file size)
#   - PNG for presentations (raster format, high DPI for screen)
#
# All figures follow naming convention:
#   fig{number}_{description}.{pdf|png}
#
# Example:
#   fig2_heatmap_dopamine_replete.pdf
#   fig2_snips_dopamine_replete.png
# ───────────────────────────────────────────────────────────────────────

print(f"\nFigure saving is currently: {'ENABLED' if SAVE_FIGS else 'DISABLED'}")
print(f"Figure output folder: {FIGSFOLDER}")
if SAVE_FIGS:
    print("All generated figures will be saved in both PDF and PNG formats.")
else:
    print("To save figures, set SAVE_FIGS = True in src/figure_config.py")
